### PR TITLE
Sequel of security

### PR DESCRIPTION
**Pull request by 47souls**
Few changes were provided.
1) Extra jsp files were removed.
2) Authentication token is generating in server side and then sending back to user.
3) Changes in user model, token field was added.
4) All methods by transforming token are in Util class.
5) Also small changes in repository and service.

### CODE REVIEW

**Comment by RoxVer** [comment]
So, we won't have column "is_active" for User anymore?

**Comment by ghost** [comment]
Hello! I checked your branch! Everything works fine. But as you changed model User, a couple of test do not work: testGetUser, testUpdateUser.

Also don't work: 
testLogout_ShouldReturnRedirectView, testLogout_LogoutHandlerGetsNullAndMethodsReturnsRedirectView
So I think you should fix this mistakes, or delet them if we don't use this tests anymore.

Also you have code that dont use. You should delet it also:
UsernamePasswordAuthenticationProvider.java - lines  36 - 45
User.java - lines 145-147, 154-156, 163-165

**Comment by ghost** [comment]
Another mistake:
User leave site, If update any page.

**Comment by ghost** [comment]
Also I have a question about token field in User model. Is it good to have that field exactly in this entity. 
As i understand Token shoud have some date expiration, so one user can have a couple of tokens.
May be much better save this tokens in separate table with fields ID and DateExpiration ?

**Comment by KostyaTk** [comment]
I need isActive field for email verification.

**Comment by ihorkazakov** [comment]
I can't login to account neither after registration or resetting password. 
I got "Invalid credentials. Please input right credentials or register." message.

**Pull request merged**
