### PR TITLE
Rvjavgt 49   implement java model for point

### PR DESCRIPTION
**Pull request by 47souls**
Changed table name to "point", empty contructor was removed.

### CODE REVIEW

**Comment by RoxVer** [comment]
Reviewed, no questions yet.

**Comment by ghost** [comment]
Reviewed

**Comment by Sabfir** [comment]
This task means points and places as well.
You have to add class Place, Point (already exists) and connections between them

**Comment by Sabfir** [comment]
Pls, do not delete pull request.
Just do what you want to do and continue to commit.

**Comment by Sabfir** [comment]
Pls, after changing and committing, answer to the comments above

**Comment by KostyaTk** [comment]
@Sabfir All required changes are added

**Comment by Sabfir** [comment]
reviewed

**Pull request merged**
